#####
POST https://ch2-ps401.et.r.appspot.com/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "name" : "hariz",
    "email" : "hariz@gmail.com",
    "password" : "12345"
}

###
GET https://ch2-ps401.et.r.appspot.com/api/v1/users/productList HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc2YWVlYjA2ZTE1MTE5MThiODM3NjciLCJpYXQiOjE3MDIyOTcyODQsImV4cCI6MTcwMjM4MzY4NH0.BQ-IfaDgFcFRGtPlYYQd9X3gr3SkDBiO8d0hWOkfYgc


